# Generated by Django 3.2.5 on 2021-08-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='tags',
            new_name='tag',
        ),
    ]
