# Generated by Django 3.2.5 on 2021-08-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_tags_card_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='url',
        ),
        migrations.AddField(
            model_name='learning_history',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.package'),
        ),
    ]
