# Generated by Django 3.2.5 on 2021-08-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210809_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_history',
            old_name='date',
            new_name='date_time',
        ),
    ]
