# Generated by Django 3.2.5 on 2021-09-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_learning_history_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
