# Generated by Django 3.2.5 on 2021-10-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_package_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='url',
        ),
    ]
