# Generated by Django 3.2.5 on 2022-01-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20220105_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning_statistics',
            name='hour',
        ),
    ]
